# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # ✅ Exécute toutes les 6 heures
  workflow_dispatch:  # ✅ Permet de déclencher l’action manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # ✅ Permet l’écriture dans le repo

    steps:
      - uses: actions/checkout@v4  # ✅ Mise à jour vers v4

      # Génération du Snake GIF & SVG
      - uses: Platane/snk@v3  # ✅ Utilisation d’une version stable
        id: snake-gif
        with:
          github_user_name: bardiotmarin
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status  # ✅ Vérifie les fichiers générés (debug)

      # Ajout et push des fichiers générés
      - name: Commit & Push changes
        run: |
          git config --global user.name "bardiotmarin"
          git config --global user.email "bardiot.marin@gmail.com"
          git add dist/*
          git commit -m "Updated Snake contribution graph" || echo "No changes to commit"
          git push oriigin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Déploiement sur la branche "output"
      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
