name: Metrics

on:
  # Planification des mises à jour quotidiennes
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optionnel) Exécuter le workflow lors des pushs sur main/master
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate dist files
        run: |
          mkdir -p dist
          echo "Updated metrics" > dist/metrics.txt

      - name: Configure Git
        run: |
          git config --global user.name "bardiotmarin"
          git config --global user.email "bardiot.marin@gmail.com"

      - name: Commit and Push changes
        run: |
          git add dist/*
          git commit -m "Updated Snake contribution graph" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bardiotmarin
          config_timezone: Europe/Minsk
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata  
          plugin_introduction: yes  
          plugin_isocalendar: yes 
          plugin_isocalendar_duration: full-year 
          plugin_languages: yes 
          plugin_languages_details: bytes-size, percentage 
          plugin_achievements: yes
          plugin_achievements_display: detailed  
          plugin_calendar: yes 
          plugin_calendar_limit: 11 
          plugin_habits: yes 
          plugin_habits_facts: yes  
          plugin_habits_charts: yes  
          plugin_licenses: yes  
          plugin_licenses_setup: npm ci 
          plugin_skyline: yes 
          plugin_skyline_year: 2022
          plugin_skyline_frames: 120 
          plugin_skyline_quality: 1  
          plugin_stargazers: yes 
          plugin_stargazers_charts_type: chartist  
          plugin_support: yes 
          plugin_topics: yes  
          plugin_topics_limit: 0
          plugin_topics_mode: icons
