name: Metrics

on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bardiotmarin
          config_timezone: Europe/Minsk
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata

          # Plugins activés avec corrections
          plugin_introduction: yes  
          plugin_isocalendar: yes 
          plugin_isocalendar_duration: full-year 
          plugin_languages: yes 
          plugin_languages_details: bytes-size, percentage 
          plugin_achievements: yes 
          plugin_achievements_threshold: bronze 
          plugin_achievements_display: detailed  
          plugin_calendar: yes 
          plugin_calendar_limit: 11 
          plugin_habits: yes 
          plugin_habits_facts: yes  
          plugin_habits_charts: yes  
          
          # Désactiver les plugins inutiles ou gourmands en ressources
          plugin_licenses: no  
          plugin_skyline: no 

          # Stargazers et Topics optimisés
          plugin_stargazers: yes 
          plugin_stargazers_charts_type: chartist  
          plugin_topics: yes  
          plugin_topics_limit: 10

          # Activer le mode debug pour plus de détails en cas d'erreur
          debug: true
