name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: bardiotmarin
          config_timezone: Europe/Minsk
          committer_message: chore: update metrics
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
          plugin_calendar: yes
          plugin_calendar_limit: 11
          plugin_habits: yes
          plugin_habits_facts: yes  
          plugin_habits_charts: yes  
          plugin_licenses: no  # Désactivé pour éviter des problèmes liés à npm ci.
          plugin_skyline: no   # Désactivé pour réduire la charge.
          debug: true
